name: REMONT
favicon: null
layout_spectrum: 1
typography_spectrum: 0.03922349284403026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#717276'
    - '#e3e0e6'
    - '#545559'
    - '#a6a6a4'
    - '#030213'
  brandStrength: 0.30595513759180903
  lightness: 0.36104057217016816
  saturation: 0.6030721478164196
  rhythmicContrast: 0.23256525746546686
purpose: []
